--CREATE USER grupo_6
--IDENTIFIED BY minha_senha123 
--DEFAULT TABLESPACE USR_LOGISTICA 
--TEMPORARY TABLESPACE temp 
--QUOTA 100M ON USR_LOGISTICA
--ACCOUNT UNLOCK;

--GRANT CREATE SESSION TO grupo_6;
--GRANT CREATE TABLE TO grupo_6;
--GRANT CREATE TABLESPACE TO grupo_6;
--GRANT UNLIMITED TABLESPACE TO grupo_6
--GRANT CREATE ANY TABLE TO grupo_6;

--CREATE TABLESPACE USR_LOGISTICA
--DATAFILE '/exemple_path/usr_logistica01.dbf' 
--SIZE 100M 
--AUTOEXTEND ON 
--NEXT 10M 
--MAXSIZE 500M;

CREATE TABLE MOTORISTAS (
  MOTORISTA_ID NUMBER(10) NOT NULL,
  NOME VARCHAR2(100) NOT NULL,
  CNH VARCHAR2(20),
  TELEFONE VARCHAR2(15),
  CONSTRAINT PK_MOTORISTA_ID PRIMARY KEY (MOTORISTA_ID)
) --TABLESPACE USR_LOGISTICA;

CREATE TABLE VEICULOS (
  VEICULO_ID NUMBER(10) NOT NULL,
  PLACA VARCHAR2(10) NOT NULL,
  MODELO VARCHAR2(100),
  CAPACIDADE_CARGA NUMBER(10,2),
  STATUS VARCHAR2(50),
  CONSTRAINT PK_VEICULO_ID PRIMARY KEY (VEICULO_ID)
) --TABLESPACE USR_LOGISTICA;

CREATE TABLE ROTAS (
  ROTA_ID NUMBER(10) NOT NULL,
  ORIGEM VARCHAR2(100),
  DESTINO VARCHAR2(100),
  DISTANCIA NUMBER(10,2),
  CONSTRAINT PK_ROTA_ID PRIMARY KEY (ROTA_ID)
) --TABLESPACE USR_LOGISTICA;

CREATE TABLE VIAGENS (
  VIAGEM_ID NUMBER(10) NOT NULL,
  VEICULO_ID NUMBER(10) NOT NULL,
  MOTORISTA_ID NUMBER(10) NOT NULL,
  ROTA_ID NUMBER(10) NOT NULL,
  DATA_PARTIDA DATE,
  DATA_CHEGADA DATE,
  STATUS VARCHAR2(50),
  CONSTRAINT PK_VIAGEM_ID PRIMARY KEY (VIAGEM_ID),
  CONSTRAINT FK_VEICULO_VIAGEM FOREIGN KEY (VEICULO_ID) REFERENCES VEICULOS (VEICULO_ID),
  CONSTRAINT FK_MOTORISTA_VIAGEM FOREIGN KEY (MOTORISTA_ID) REFERENCES MOTORISTAS (MOTORISTA_ID),
  CONSTRAINT FK_ROTA_VIAGEM FOREIGN KEY (ROTA_ID) REFERENCES ROTAS (ROTA_ID)
) --TABLESPACE USR_LOGISTICA;

CREATE TABLE CLIENTES (
  CLIENTE_ID NUMBER(10) NOT NULL,
  NOME VARCHAR2(100) NOT NULL,
  TELEFONE VARCHAR2(15) NOT NULL,
  EMAIL VARCHAR2(100),
  ENDERECO VARCHAR2(255),
  CONSTRAINT PK_CLIENTE_ID PRIMARY KEY (CLIENTE_ID)
) --TABLESPACE USR_LOGISTICA;

CREATE TABLE ENTREGAS (
  ENTREGA_ID NUMBER(10) NOT NULL,
  VIAGEM_ID NUMBER(10) NOT NULL,
  CLIENTE_ID NUMBER(10) NOT NULL,
  ENDERECO_ENTREGA VARCHAR2(255),
  STATUS VARCHAR2(50),
  CONSTRAINT PK_ENTREGA_ID PRIMARY KEY (ENTREGA_ID),
  CONSTRAINT FK_VIAGEM_ENTREGA FOREIGN KEY (VIAGEM_ID) REFERENCES VIAGENS (VIAGEM_ID),
  CONSTRAINT FK_CLIENTE_ENTREGA FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (CLIENTE_ID)
) --TABLESPACE USR_LOGISTICA;
